const express = require("express");
// const  feeController = require("../controllers/feeController");
// const fileUpload = require("../middleware/fileUpload");
const router = express.Router();
// router.get('/',feeController.getFees);
// router.get('/create',fileUpload,feeController.createFees);
// router.get('/update/:feeId',fileUpload,feeController.updateFees);
// router.get('/:feeId',feeController.fee);
// router.get('/fee/:studentId',fileUpload,feeController.createFeeDetails);
// router.get('/fee/:studentId',feeController.createFeeDetails);
module.exports= router;